disabled_rules: # các rule loại bỏ
  - trailing_whitespace
opt_in_rules: # các rule được thêm vào
  - control_statement
  - empty_count
  - trailing_newline
  - colon
  - comma
excluded: # đường dẫn bỏ qua việc kiểm tra
  - Pods
  - MovieMVVM\Platform\API\Response\HTTPStatusCode.swift

# hiển thị warning khi sử dụng force casting
force_cast: warning
force_try:
  severity: warning
  
# giới hạn
function_body_length:
  warning: 50
  error: 60
line_length: 130

identifier_name:
  min_length: 2

reporter: "xcode"
